<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
    <AssemblyName>TorrentCs</AssemblyName>
    <RootNamespace>TorrentCs</RootNamespace>
    <Description>A BitTorrent library running on .NET 6 and above.</Description>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Transport/ClientPeerIds.txt" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TorrentCs.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BencodeNET" Version="3.0.1" />
    <PackageReference Include="Mono.Nat" Version="3.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
  </ItemGroup>

</Project>
